name: quality
on:
  push:
  pull_request:
jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true
          python -m pip install -e ./veildaemon[dev]
      - name: Import smoke
        run: |
          python - << 'PY'
          import importlib
          mods = [
            'veildaemon.event_bus',
            'veildaemon.stage_director',
            'veildaemon.tts.manager',
            'veildaemon.apps.api.wick_db',
            'veildaemon.apps.api.wick_obsidian',
            'veildaemon.apps.watchers.twitch_chat_watcher',
            'veildaemon.apps.packs.pack_loader',
          ]
          for m in mods:
            importlib.import_module(m)
          print('SMOKE OK')
          PY
      - name: Generate NAV
        run: |
          python tools/gen_nav.py
      - name: Fail if NAV drift
        run: |
          git diff --quiet || (echo "NAV changed; run tools/gen_nav.py and commit." && exit 1)
      - name: Fail on tabs/nbspace/zwsp in docs
        run: |
          set -e
          pattern='[\t\u00A0\u200B\uFEFF]'
          matches=$(git ls-files '*.md' '*.yml' '*.yaml' | xargs -I{} grep -nP "$pattern" {} || true)
          if [ -n "$matches" ]; then
            echo "Disallowed whitespace chars found:" >&2
            echo "$matches" >&2
            exit 1
          fi

      - name: Lint & format check (pinned)
        run: |
          python -m ruff check veildaemon
          python -m black --check veildaemon
          python -m isort --check-only veildaemon

